### ISSUE TITLE
Account Settings

### ISSUE THREAD

**Issue by EdwardTo** [ucsdcirclek/konnection#11]
Hey y'all, 

It's Vivian using Edward's github account. I'm using my historian@ucsdck.org email for my CKI account, but it still has Tim's information in it for some reason. I'm trying to change those settings, but it won't let me. Please fix it so I won't have Tyra Banks as my account profile picture!

**Comment by tanbrian** [comment]
Username and profile picture have been changed, but a 500 was thrown when the profile picture was updated, need to look into this. Likely the result of a bug in the picture cropping logic in the users controller.

**Comment by tanbrian** [comment]
Fixed with e63b2e61737d7463e34f36a4cb17f3cec0468cf5. I screwed up and thought that all images have EXIF data. Some don't, and those have their height and width values automatically computed. Closing both profile pic related issues for now, if there's another reason why they aren't uploading, then I'll reopen this one.
