### ISSUE TITLE
Event side calendar doesn't group events by dates

### ISSUE THREAD

**Issue by josephnle** [ucsdcirclek/konnection#23]
The logic for the events side calendar currently groups events by day and NOT by date. Sorry, this is definitely my fault lol.

Example: Masquerade Ball Photoshoot and Howl-o-Ween Canine Carnival are both on A Saturday but NOT the same date.

<img width="241" alt="side-calendar" src="https://cloud.githubusercontent.com/assets/2822954/10566643/1133498c-75a2-11e5-9fa4-be4cf519a4ff.png">

**Comment by tanbrian** [comment]
Honestly I think changing the range of upcoming events from a week from now to six days instead is fine. This bug only happens for events on the current day a week from now so another possible fix is having two sections labeled with the same weekday, but that's a bit weird because users might not be sure which of of the two sections labeled with the same weekday is the "closest" one.

Also this fix is way easier lol. de86579cfe749a4c7d0aa174c95767f31ce891a5
