### ISSUE TITLE
Double-clicking calendar link causes a crash

### ISSUE THREAD

**Issue by tanbrian** [ucsdcirclek/konnection#30]
Double-clicking the calendar link on the navigation bar causes an error message to show up, but the calendar reloads directly after the alert shows so the calendar is still usable, but definitely not good. Likely a problem with the AJAX call in `calendar.js`. Error message logged in the web inspector console shows that the properties of a null object is being accessed.

**Comment by josephnle** [comment]
@tanbrian What browser (version as well please)? I can't reproduce.

**Comment by tanbrian** [comment]
Safari v9.1, Chrome v50.0. To be a bit more specific, the error alert pops up when you click on the calendar link, then click on it again while it's still loading.

**Comment by josephnle** [comment]
Oh, just got it because my internet is slow as heck.

Hacky fix would maybe be to just make the calendar link to `#` when the user is on the calendar page. Not sure what the actual cause is because it's supposed to load the whole page again, yet this seems like a JS issue. Maybe Safari does a thing where it just runs the JS again instead of refreshing the whole page if you request the same page again?
