### ISSUE TITLE
CERFs having problems

### ISSUE THREAD

**Issue by reggiewumo** [ucsdcirclek/konnection#38]
Looking at the pending cerfs from the admin bar comes up with a 'Whoops, looks like something went wrong'
edit:
production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/konnection/storage/framework/views/670955b78581b73ac20a248316624ebc:23

**Comment by josephnle** [comment]
You should be able to see the error in the error log

**Comment by tanbrian** [comment]
Turned out someone was using the feature to create CERFs without an associated event on the calendar to create events with empty titles, causing the null objects. Not sure how this was done because I added required validation rules on that feature. Also, the user made like twelve or so totally empty CERFs. Maybe a bot?

For now this issue is fixed, but need to figure out how the user did that.

**Comment by josephnle** [comment]
Each CERF should be associated with a user. Can you trace it back? @tanbrian @reggiewumo

**Comment by tanbrian** [comment]
Already deleted the records but I remember that the user ID was 94. Account looks legit with an avatar pic and normal user info, so not too sure.

**Comment by reggiewumo** [comment]
More error, this time the whoops screen happens after setting tags for the cerfs
