### ISSUE TITLE
Migrate to Bootstrap v4

### ISSUE THREAD

**Issue by josephnle** [ucsdcirclek/konnection#46]
The current website is using the [Bourbon Neat](http://neat.bourbon.io) SCSS framework. It's cool stuff and it sounded cutting-edge and ultra-techy when I was a young dev. Unfortunately, this stuff is also kind of hard to work with and isn't as easy to understand and utilize as Bootstrap. Bootstrap also simply has a larger community backing it - which is important for longterm projects such as this.

I'm proposing that we migrate the entire site to Bootstrap v4 when @reggiewumo starts making the design for the next term. Shouldn't be too hard! It's just redoing the templates.

**Comment by tanbrian** [comment]
Yeah, let's do that. I think the Neat framework is a clean and simple solution to laying out our pages because it keeps styles where they should be instead of putting a bunch of extra classes in our markup, and also because it can do everything we needed it to do so I never really saw a problem. With that said, the Neat documentation really sucks compared to Bootstrap and the new stuff in v4 sounds like it's going to make life easy (moved to Sass yes finally) so Bootstrap is definitely the best way to go.
