### ISSUE TITLE
CERFs form crashes on event tags page

### ISSUE THREAD

**Issue by reggiewumo** [ucsdcirclek/konnection#51]
production.ERROR: exception 'Illuminate\Foundation\Validation\ValidationException' with message 'The given data failed to pass validation.' in /var/www/konnection/bootstrap/cache/compiled.php:5519

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`circlek1_konnection`.`events_assigned_tags`, CONSTRAINT `events_assigned_tags_cerf_id_foreign` FOREIGN KEY (`cerf_id`) REFERENCES `users` (`id`)) (SQL: insert into events_assigned_tags (event_id, tag_id, cerf_id, approved) values (1136, 1, 386, false);)' in /var/www/konnection/vendor/laravel/framework/src/Illuminate/Database/Connection.php:680

someone had problems submitting a cerf but it was resolved later so idk if its a problem

**Comment by reggiewumo** [comment]
Getting this error as well:
[2016-06-06 00:33:29] production.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`circlek1_konnection`.`events_assigned_tags`, CONSTRAINT `events_assigned_tags_cerf_id_foreign` FOREIGN KEY (`cerf_id`) REFERENCES `users` (`id`))' in /var/www/konnection/vendor/laravel/framework/src/Illuminate/Database/Connection.php:408

**Comment by reggiewumo** [comment]
Looks like the cerf submits the first time, but without tags. Redoing the cerf again lets it go through with tags and no errors.

**Comment by tanbrian** [comment]
I don't think this is a minor error, any 500 error is a pretty big problem. Could you be a bit more detailed about how to reproduce the error message? I'm pretty sure there's validation on the tags page in the CERFs form.

**Comment by reggiewumo** [comment]
I'm not sure about specifics, and it's only happened to 2 people - the first was for wednesday's ark event and the other was for a nonevent - but the first time would cause the error, and then after going back and re-filling out the cerf there was no error.

**Comment by apwei** [comment]
Hi! Idk if you're still in the process of fixing this but Esther had trouble getting past the event tags page and once she did, she wasn't able to add any members. This is probably why I'm seeing two incomplete CERFs on for the same event. I've also had a similar problem in the past where submitted CERFs would show up as two on the page (one blank and one with data), and the second one would disappear sometime after I approve the first one. Since I check CERFs anyways I'm not so worried about the second issue though. Thank you reading this! -Alexandra
